language: java
sudo: required
dist: trusty

before_install:
  - sudo apt-key adv --keyserver keys.gnupg.net --recv 6DA70622
  - sudo echo "deb http://downloads.ortussolutions.com/debs/noarch /" | sudo tee -a /etc/apt/sources.list.d/commandbox.list

install:
  #Commandbox setup
  - box install
  - box server start port=49616 rewritesEnable=false openBrowser=false

before_script:
  - curl http://localhost:49616/

script: >
    testResults="echo $(box testbox run)";
    echo "$testResults";
    if grep -i "\[Failures: [1-9][0-9]\?\]\|<t[^>]*>\|<b[^>]*>" <<< $testResults;  then exit 1; fi
